pipeline
{


    agent any
    stages
    {

            stage("Print your messeage")

                {

                     steps { echo 'hello message' }
                }

                 stage("CPU Useage")

                {

                     steps { echo 'top usage' }
                }

    }



}
